spring:
  cache:
    cache-names: query-result, demo
    caffeine:
      spec: maximumSize=500, expireAfterAccess=30s
logging:
  pattern:
    console: "%-5level - %msg%n"
  level:
    - error
    - heyikan=ALL
